# Generated by Django 2.2.5 on 2019-09-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaka_grupe', models.CharField(max_length=10)),
                ('smer', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'grupe',
            },
        ),
        migrations.CreateModel(
            name='Nalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('lozinka', models.CharField(max_length=100, null=True)),
                ('uloga', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'nalozi',
            },
        ),
        migrations.CreateModel(
            name='Nastavnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('titula', models.CharField(max_length=20, null=True)),
                ('zvanje', models.CharField(max_length=40, null=True)),
                ('nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Nalog')),
            ],
            options={
                'verbose_name_plural': 'nastavnici',
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('espb', models.IntegerField(null=True)),
                ('semestar_po_programu', models.IntegerField(null=True)),
                ('fond_predavanja', models.IntegerField(null=True)),
                ('fond_vezbe', models.IntegerField(null=True)),
                ('sifra', models.CharField(default='0', max_length=15)),
                ('izborni', models.BooleanField(default=False)),
                ('opis', models.TextField(null=True)),
                ('opis_fajl', models.FileField(null=True, upload_to='opispredmeta/')),
            ],
            options={
                'verbose_name_plural': 'predmeti',
            },
        ),
        migrations.CreateModel(
            name='RasporedNastave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_unosa', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'rasporedi nastave',
            },
        ),
        migrations.CreateModel(
            name='RasporedPolaganja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'rasporedi polaganja',
            },
        ),
        migrations.CreateModel(
            name='Semestar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(choices=[('parni', 'parni'), ('neparni', 'neparni')], max_length=20)),
                ('skolska_godina_pocetak', models.IntegerField()),
                ('skolska_godina_kraj', models.IntegerField()),
                ('aktivan', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'semestri',
            },
        ),
        migrations.CreateModel(
            name='VazniDatumi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(max_length=200)),
                ('oznaka', models.CharField(max_length=200)),
                ('datum_od', models.DateField(null=True)),
                ('datum_do', models.DateField(null=True)),
                ('okvirno', models.CharField(max_length=200, null=True)),
                ('skolska_godina', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'vazni datumi',
            },
        ),
        migrations.CreateModel(
            name='TerminPolaganja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucionice', models.CharField(max_length=100)),
                ('pocetak', models.TimeField()),
                ('zavrsetak', models.TimeField()),
                ('datum', models.DateField()),
                ('dan', models.CharField(max_length=100)),
                ('nastavnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Nastavnik')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Predmet')),
                ('raspored_polaganja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.RasporedPolaganja')),
            ],
            options={
                'verbose_name_plural': 'termini polaganja',
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaka_ucionice', models.CharField(max_length=50)),
                ('pocetak', models.TimeField()),
                ('zavrsetak', models.TimeField()),
                ('dan', models.CharField(max_length=15)),
                ('tip_nastave', models.CharField(max_length=15)),
                ('grupe', models.ManyToManyField(to='studserviceapp.Grupa')),
                ('nastavnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Nastavnik')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Predmet')),
                ('raspored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.RasporedNastave')),
            ],
            options={
                'verbose_name_plural': 'termini',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('broj_indeksa', models.IntegerField()),
                ('godina_upisa', models.IntegerField()),
                ('smer', models.CharField(max_length=20)),
                ('icon', models.ImageField(default='/media/no-image.gif', upload_to='media')),
                ('grupa', models.ManyToManyField(to='studserviceapp.Grupa')),
                ('nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Nalog')),
            ],
            options={
                'verbose_name_plural': 'studenti',
            },
        ),
        migrations.CreateModel(
            name='Slusa_Ponovac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nastavnici', models.ManyToManyField(to='studserviceapp.Nastavnik')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Predmet')),
                ('semestar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Semestar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Student')),
            ],
            options={
                'verbose_name_plural': 'ponovci',
            },
        ),
        migrations.AddField(
            model_name='rasporedpolaganja',
            name='vazan_datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.VazniDatumi'),
        ),
        migrations.AddField(
            model_name='rasporednastave',
            name='semestar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studserviceapp.Semestar'),
        ),
        migrations.CreateModel(
            name='Obavestenje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('datum_postavljanja', models.DateTimeField()),
                ('tekst', models.CharField(max_length=1000)),
                ('fajl', models.FileField(upload_to='obavestenja/')),
                ('postavio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Nalog')),
            ],
            options={
                'verbose_name_plural': 'obavestenja',
            },
        ),
        migrations.AddField(
            model_name='nastavnik',
            name='predmet',
            field=models.ManyToManyField(to='studserviceapp.Predmet'),
        ),
        migrations.CreateModel(
            name='Konsultacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(max_length=50)),
                ('vreme_od', models.TimeField()),
                ('vreme_do', models.TimeField()),
                ('dan', models.CharField(max_length=15)),
                ('nastavnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Nastavnik')),
                ('predmet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.Predmet')),
            ],
            options={
                'verbose_name_plural': 'konsultacije',
            },
        ),
        migrations.CreateModel(
            name='IzbornaGrupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaka_grupe', models.CharField(max_length=20)),
                ('oznaka_semestra', models.IntegerField()),
                ('kapacitet', models.IntegerField()),
                ('smer', models.CharField(max_length=20)),
                ('aktivna', models.BooleanField()),
                ('predmeti', models.ManyToManyField(to='studserviceapp.Predmet')),
                ('za_semestar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Semestar')),
            ],
            options={
                'verbose_name_plural': 'Izborne grupe',
            },
        ),
        migrations.CreateModel(
            name='IzborGrupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostvarenoESPB', models.IntegerField()),
                ('upisujeESPB', models.IntegerField()),
                ('broj_polozenih_ispita', models.IntegerField()),
                ('upisuje_semestar', models.IntegerField()),
                ('prvi_put_upisuje_semestar', models.BooleanField()),
                ('nacin_placanja', models.CharField(max_length=30)),
                ('upisan', models.BooleanField()),
                ('izabrana_grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.IzbornaGrupa')),
                ('nepolozeni_predmeti', models.ManyToManyField(to='studserviceapp.Predmet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Student')),
            ],
            options={
                'verbose_name_plural': 'Izbori grupa',
            },
        ),
        migrations.AddField(
            model_name='grupa',
            name='semestar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studserviceapp.Semestar'),
        ),
    ]
