# Generated by Django 2.2.5 on 2019-09-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obavestenje',
            name='fajl',
            field=models.FileField(upload_to='fajlovi_obavestenja/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='icon',
            field=models.CharField(max_length=400),
        ),
    ]
